spring:
  application:
    name: microservice-msi-example
server:
  port: 9999
  contextPath: /microservice-msi-example
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
eureka: 
  client: 
    service-url: 
      defaultZone: http://discovery:8761/eureka

